### ISSUE TITLE
how to use offline

### ISSUE THREAD

**Issue by ehartford** [Aspie96/gpt-4chan-model#1]
can you please show how to use it offline?  I want to play with the model.

**Comment by ehartford** [comment]
I download the model from magnet:?xt=urn:btih:ad8bf65d19d705767f87219f3ccd1075770e80fc&dn=gpt4chan_model&tr=http%3a%2f%2fbt1.archive.org%3a6969%2fannounce&tr=http%3a%2f%2fbt2.archive.org%3a6969%2fannounce&ws=http%3a%2f%2fia601400.us.archive.org%2f24%2fitems%2f&ws=https%3a%2f%2farchive.org%2fdownload%2f&ws=https%3a%2f%2fia601400.us.archive.org&ws=https%3a%2f%2fia801400.us.archive.org and extract into the repository directory?

**Comment by Delcos** [comment]
This isn't the entire thing, you need the tokenizer and the entire vocab which aren't here and can't be found (from what I've found). This model is pretty old now anyways and you'd get better performance with pretty much anything. I have a single script that let's you run these on my github if you still want to try out LLMs.

**Comment by Aspie96** [comment]
The tokenizer is the same as GPT-2 and GPT-J. I have never used the model myself, but I have been told that it does run. Please see (not by me, it was posted on 4chan): https://pastebin.com/g7rSaCfw

**Comment by ehartford** [comment]
I was successful at running it

**Comment by Aspie96** [comment]
Nice!

**Comment by Delcos** [comment]
> I was successful at running it

Does it preform well? What is the application btw? Deployment location I mean, I've not gotten very good results overall.

**Comment by ehartford** [comment]
It's because, gpt-4chan was expecting some context such as a /pol/ thread.  It wasn't designed for conversation.
My idea was to integrate it with https://getleon.ai/ and have an evil Alexa on my computer that will abuse me anytime I ask it a question.
But gpt-4chan didn't seem great for that purpose, I think I would need to make a new model to achieve that.
